pipe:
  #- lang_id        # Identifies the language of the text
  #- acronyms       # Identifies the acronyms of the text
  - lemmas          # Creates lemmas from the text
  - ngrams          # Generates n-grams from the text
  - embeddings      # Generates BERT embeddings
  - ner_generic     # Identifies generic named entities (e.g. person, location, organization)
  - ner_specific    # Identifies specific named entities (e.g. Apple, Microsoft, New York)

options_pipe:
  spaCy_model: 'en_core_web_md'
  lang: 'en'
  valid_POS: ['VERB', 'NOUN', 'ADJ', 'PROPN']
  gensim_phraser_min_count: 2
  gensim_phraser_threshold: 20
  sentence_transformer_model: "paraphrase-distilroberta-base-v2"
  bath_size_embeddings: 128
  aggregate_embeddings : False
  use_gpu: True
  
langs_dft: 
  spaCy_model_dft_en: 'en_core_web_md'
  spaCy_model_dft_es: 'es_core_news_md'


